import 'dotenv/config';import express from'express';import helmet from'helmet';import jwt from'jsonwebtoken';import Database from'better-sqlite3';import{randomBytes,scryptSync,timingSafeEqual,createCipheriv,createDecipheriv,createHash}from'node:crypto';import{mkdirSync,readFileSync,existsSync}from'node:fs';import{dirname,resolve}from'node:path';import{z}from'zod';import{createToolsRouter}from'./tools.js';import{createRouterOsRouter}from'./routeros.js';
const required=['JWT_SECRET','ADMIN_USERNAME'];for(const k of required)if(!process.env[k]||process.env[k].length<3)throw new Error(`Missing/weak ${k}`);if(process.env.JWT_SECRET.length<32)throw new Error('JWT_SECRET must be >=32 chars');const TARGET_FW='8.7.4',TARGET_SHA256='b959c66ec28d1c26ce0eac9122cc345b1fe92450df74a6cf627f5cb28e83323c',FACTORY_IP='192.168.172.1';
const intEnv=(name,def,min=1,max=65535)=>{const n=Number(process.env[name]??def);return Number.isInteger(n)&&n>=min&&n<=max?n:def};
const CPE_NETWORK_PROFILE={
  vlanId:intEnv('CPE_VLAN_ID',87,1,4094),
  lanIp:process.env.CPE_LAN_IP||'192.168.1.254',
  lanNetmask:process.env.CPE_LAN_NETMASK||'255.255.255.0',
  dhcpStart:process.env.CPE_DHCP_START||'192.168.1.10',
  dhcpEnd:process.env.CPE_DHCP_END||'192.168.1.50',
  dhcpLease:intEnv('CPE_DHCP_LEASE',600,60,86400),
  pppoeMtu:intEnv('CPE_PPPOE_MTU',1450,576,1500),
  pppoeMru:intEnv('CPE_PPPOE_MRU',1450,576,1500),
  watchdogHost:process.env.CPE_WATCHDOG_HOST||'10.0.0.254',
  ntpServer:process.env.CPE_NTP_SERVER||'10.0.0.254',
  sshPort:intEnv('CPE_SSH_PORT',22,1,65535),
  discoveryPort:intEnv('CPE_DISCOVERY_PORT',10001,1,65535)
};
const keyPath=process.env.SECRETS_KEY_FILE||'/run/secrets/cdanet_master_key';let MASTER_KEY;try{MASTER_KEY=Buffer.from(readFileSync(keyPath,'utf8').trim(),'base64')}catch{throw new Error('Secrets master key unavailable')};if(MASTER_KEY.length!==32)throw new Error('Secrets master key must decode to 32 bytes');const seal=v=>{const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',MASTER_KEY,iv),ct=Buffer.concat([c.update(v,'utf8'),c.final()]);return`${iv.toString('base64')}.${c.getAuthTag().toString('base64')}.${ct.toString('base64')}`},open=v=>{const[iv,tag,ct]=v.split('.').map(x=>Buffer.from(x,'base64')),d=createDecipheriv('aes-256-gcm',MASTER_KEY,iv);d.setAuthTag(tag);return Buffer.concat([d.update(ct),d.final()]).toString('utf8')};
const dbPath=process.env.DB_PATH||'./data/cdanet.sqlite';mkdirSync(dirname(dbPath),{recursive:true});const db=new Database(dbPath);db.pragma('journal_mode = WAL');db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN('admin','installer')),active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS audits(id INTEGER PRIMARY KEY,created_at TEXT NOT NULL,user_id INTEGER NOT NULL,ssid TEXT NOT NULL,pppoe_user TEXT NOT NULL,model TEXT NOT NULL,mac TEXT NOT NULL,serial TEXT NOT NULL,result TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id));CREATE TABLE IF NOT EXISTS wireless_secrets(ssid TEXT PRIMARY KEY,wpa2_ciphertext TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS provision_profiles(model TEXT NOT NULL,firmware TEXT NOT NULL,board_match TEXT NOT NULL DEFAULT '',template_ciphertext TEXT NOT NULL,template_sha256 TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(model,firmware));`);const hash=p=>{const s=randomBytes(16).toString('hex');return`${s}:${scryptSync(p,s,64).toString('hex')}`},verify=(p,h)=>{const[s,x]=h.split(':'),a=Buffer.from(x,'hex'),b=scryptSync(p,s,64);return a.length===b.length&&timingSafeEqual(a,b)};
const adminCount=db.prepare("SELECT count(*) n FROM users WHERE role='admin'").get().n;if(adminCount===0){const p=process.env.ADMIN_PASSWORD;if(!p||p.length<14)throw new Error('First boot requires ADMIN_PASSWORD >=14 chars');db.prepare('INSERT INTO users(username,password_hash,role,created_at) VALUES(?,?,?,?)').run(process.env.ADMIN_USERNAME,hash(p),'admin',new Date().toISOString())}
const app=express();app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:false}));app.use((req,res,next)=>{const o=req.headers.origin||'';const allowed=new Set([process.env.ALLOWED_ORIGIN||'','https://localhost','http://localhost','capacitor://localhost']);if(o&&allowed.has(o)){res.setHeader('Access-Control-Allow-Origin',o);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Authorization, Content-Type, X-CDA-Client');res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,DELETE,OPTIONS');}if(req.method==='OPTIONS')return allowed.has(o)?res.sendStatus(204):res.sendStatus(403);next()});app.use(express.json({limit:'384kb'}));const auth=(req,res,next)=>{try{req.user=jwt.verify((req.headers.authorization||'').replace(/^Bearer /,''),process.env.JWT_SECRET);next()}catch{return res.status(401).json({error:'unauthorized'})}},admin=(req,res,next)=>req.user.role==='admin'?next():res.status(403).json({error:'forbidden'});app.use('/api/tools',createToolsRouter(auth));app.use('/api/routeros',createRouterOsRouter(auth));const ssid=z.string().regex(/^CDA-NET-N(?:[2-9]|[1-9][0-9])-D(?:0[1-9]|[1-9][0-9])$/);
app.get('/api/health',(req,res)=>res.json({ok:true,service:'cda-net-provisioning',version:'0.4.1',targetFirmware:TARGET_FW,mobileProvisioning:true,webTools:true,webBridge:true}));app.post('/api/login',(req,res)=>{const b=z.object({username:z.string(),password:z.string().min(8)}).safeParse(req.body);if(!b.success)return res.status(400).json({error:'invalid_request'});const u=db.prepare('SELECT * FROM users WHERE username=? AND active=1').get(b.data.username);if(!u||!verify(b.data.password,u.password_hash))return res.status(401).json({error:'invalid_credentials'});res.json({token:jwt.sign({sub:u.id,username:u.username,role:u.role},process.env.JWT_SECRET,{expiresIn:'2h'}),user:{username:u.username,role:u.role}})});
app.get('/api/wireless-networks',auth,(req,res)=>res.json(db.prepare('SELECT ssid,updated_at FROM wireless_secrets ORDER BY ssid').all()));app.put('/api/admin/wireless-networks/:ssid',auth,admin,(req,res)=>{const s=ssid.safeParse(req.params.ssid),b=z.object({wpa2Password:z.string().min(8).max(63)}).safeParse(req.body);if(!s.success||!b.success)return res.status(400).json({error:'invalid_request'});db.prepare('INSERT INTO wireless_secrets(ssid,wpa2_ciphertext,updated_at) VALUES(?,?,?) ON CONFLICT(ssid) DO UPDATE SET wpa2_ciphertext=excluded.wpa2_ciphertext,updated_at=excluded.updated_at').run(s.data,seal(b.data.wpa2Password),new Date().toISOString());res.json({ok:true,ssid:s.data})});app.delete('/api/admin/wireless-networks/:ssid',auth,admin,(req,res)=>{const s=ssid.safeParse(req.params.ssid);if(!s.success)return res.status(400).json({error:'invalid_request'});db.prepare('DELETE FROM wireless_secrets WHERE ssid=?').run(s.data);res.json({ok:true})});
app.post('/api/users',auth,admin,(req,res)=>{const b=z.object({username:z.string().min(3).max(80).regex(/^[A-Za-z0-9._-]+$/),password:z.string().min(12).max(200)}).safeParse(req.body);if(!b.success)return res.status(400).json({error:'invalid_request'});try{db.prepare('INSERT INTO users(username,password_hash,role,created_at) VALUES(?,?,?,?)').run(b.data.username,hash(b.data.password),'installer',new Date().toISOString());res.status(201).json({ok:true})}catch{return res.status(409).json({error:'username_exists'})}});
const models=['NanoStation Loco 5AC','NanoStation 5AC','NanoBeam 5AC','LiteBeam 5AC','PowerBeam 5AC'];
const profileKey=z.object({model:z.enum(models),firmware:z.enum(['8.7.4'])});
app.get('/api/admin/provision-profiles',auth,admin,(req,res)=>res.json(db.prepare('SELECT model,firmware,board_match boardMatch,template_sha256 sha256,updated_at updatedAt FROM provision_profiles ORDER BY model,firmware').all()));
app.put('/api/admin/provision-profiles/:model/:firmware',auth,admin,(req,res)=>{const k=profileKey.safeParse(req.params),b=z.object({template:z.string().min(64).max(300000),boardMatch:z.string().min(2).max(240)}).safeParse(req.body);if(!k.success||!b.success)return res.status(400).json({error:'invalid_request'});if(!b.data.template.includes('system.cfg.version='))return res.status(400).json({error:'profile_not_system_cfg'});const sha=createHash('sha256').update(b.data.template).digest('hex'),now=new Date().toISOString();db.prepare('INSERT INTO provision_profiles(model,firmware,board_match,template_ciphertext,template_sha256,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(model,firmware) DO UPDATE SET board_match=excluded.board_match,template_ciphertext=excluded.template_ciphertext,template_sha256=excluded.template_sha256,updated_at=excluded.updated_at').run(k.data.model,k.data.firmware,b.data.boardMatch,seal(b.data.template),sha,now);res.json({ok:true,model:k.data.model,firmware:k.data.firmware,sha256:sha,updatedAt:now})});
app.delete('/api/admin/provision-profiles/:model/:firmware',auth,admin,(req,res)=>{const k=profileKey.safeParse(req.params);if(!k.success)return res.status(400).json({error:'invalid_request'});db.prepare('DELETE FROM provision_profiles WHERE model=? AND firmware=?').run(k.data.model,k.data.firmware);res.json({ok:true})});const schema=z.object({model:z.enum(models),firmware:z.enum(['8.7.4','8.7.11','8.7.25']),mac:z.string().min(11).max(20),serial:z.string().min(1).max(128),ssid,pppoeUser:z.string().min(1).max(128),pppoePassword:z.string().min(1).max(200)}).strict();const resolveWpa=s=>{const r=db.prepare('SELECT wpa2_ciphertext FROM wireless_secrets WHERE ssid=?').get(s);if(!r)throw new Error('ssid_secret_not_configured');return open(r.wpa2_ciphertext)};
const cleanBackendSecret=(name,max=4096)=>{const v=process.env[name]||'';if(v.includes('\n')||v.includes('\r')||v.length>max)throw new Error('invalid_runtime_secret');return v};
app.post('/api/mobile/provision-package',auth,(req,res)=>{if(!['android-native-v0.2','android-native-v0.3','android-native-v0.4','web-bridge-v0.3','web-bridge-v0.4'].includes(req.get('X-CDA-Client')||''))return res.status(403).json({error:'trusted_client_required'});const b=schema.safeParse(req.body);if(!b.success)return res.status(400).json({error:'invalid_request'});const x=b.data;let wpa2;try{wpa2=resolveWpa(x.ssid)}catch{return res.status(409).json({error:'ssid_secret_not_configured'})}const p=db.prepare('SELECT * FROM provision_profiles WHERE model=? AND firmware=?').get(x.model,TARGET_FW);if(!p){wpa2=undefined;return res.status(409).json({error:'provision_profile_missing',model:x.model,firmware:TARGET_FW})}let template;try{template=open(p.template_ciphertext)}catch{wpa2=undefined;return res.status(500).json({error:'profile_decrypt_failed'})}const deviceUser=cleanBackendSecret('CPE_ADMIN_USERNAME',80)||'ubnt',devicePassword=cleanBackendSecret('CPE_ADMIN_PASSWORD',200),uisp=cleanBackendSecret('UISP_ENROLLMENT',4096),snmp=cleanBackendSecret('SNMP_COMMUNITY',200);if(!devicePassword){wpa2=undefined;return res.status(503).json({error:'cpe_admin_secret_missing'})}const required=[['${WPA2_PSK}',wpa2],['${PPPOE_USER}',x.pppoeUser],['${PPPOE_PASSWORD}',x.pppoePassword],['${UISP_ENROLLMENT}',uisp],['${SNMP_COMMUNITY}',snmp]];for(const [ph,val] of required){if(template.includes(ph)&&!val){wpa2=undefined;return res.status(503).json({error:'runtime_secret_missing',placeholder:ph})}}const expiresAt=new Date(Date.now()+10*60*1000).toISOString();res.setHeader('Cache-Control','no-store');res.json({ok:true,packageVersion:1,expiresAt,factoryIp:FACTORY_IP,targetFirmware:TARGET_FW,expectedDevice:{model:x.model,reportedFirmware:x.firmware,mac:x.mac,serial:x.serial},boardMatch:p.board_match||'',profileSha256:p.template_sha256,profileTemplate:template,device:{username:deviceUser,password:devicePassword},wireless:{ssid:x.ssid,password:wpa2},pppoe:{username:x.pppoeUser,password:x.pppoePassword},management:{httpPort:20080,httpsPort:20443},networkProfile:CPE_NETWORK_PROFILE,uispEnrollment:uisp,snmpCommunity:snmp});wpa2=undefined;template=undefined});
app.post('/api/provision/dry-run',auth,(req,res)=>{const b=schema.safeParse(req.body);if(!b.success)return res.status(400).json({error:'invalid_request'});const configured=!!db.prepare('SELECT 1 FROM wireless_secrets WHERE ssid=?').get(b.data.ssid);res.json({ok:true,mode:'dry-run',ssid:b.data.ssid,wpa2SecretConfigured:configured,secretExposed:false,targetFirmware:TARGET_FW,networkProfile:CPE_NETWORK_PROFILE})});
app.post('/api/provision/apply',auth,async(req,res)=>{const b=schema.safeParse(req.body);if(!b.success)return res.status(400).json({error:'invalid_request'});const x=b.data;let wpa2;try{wpa2=resolveWpa(x.ssid)}catch{return res.status(409).json({error:'ssid_secret_not_configured'})}if(process.env.PROVISIONING_MODE!=='lab-apply')return res.status(423).json({error:'apply_locked'});if(!process.env.BRIDGE_URL)return res.status(503).json({error:'bridge_not_configured'});try{const r=await fetch(`${process.env.BRIDGE_URL.replace(/\/$/,'')}/provision`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${process.env.BRIDGE_TOKEN||''}`},body:JSON.stringify({factoryManagement:{ip:FACTORY_IP},expectedDevice:{model:x.model,reportedFirmware:x.firmware,mac:x.mac,serial:x.serial},wireless:{mode:'station',security:'WPA2-AES',ssid:x.ssid,password:wpa2},network:{mode:'router',wan:'wireless',profile:CPE_NETWORK_PROFILE,pppoe:{username:x.pppoeUser,password:x.pppoePassword}},management:{http:{port:20080},https:{port:20443}}})});wpa2=undefined;const out=await r.json().catch(()=>({})),ok=r.ok&&out.ok===true;db.prepare('INSERT INTO audits(created_at,user_id,ssid,pppoe_user,model,mac,serial,result) VALUES(?,?,?,?,?,?,?,?)').run(new Date().toISOString(),req.user.sub,x.ssid,x.pppoeUser,x.model,x.mac,x.serial,ok?'success':'failed');return res.status(ok?200:502).json({ok,stages:out.stages||[]})}catch{wpa2=undefined;return res.status(502).json({ok:false,error:'bridge_unreachable'})}});app.get('/api/audits',auth,(req,res)=>res.json(req.user.role==='admin'?db.prepare('SELECT a.*,u.username installer FROM audits a JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 500').all():db.prepare('SELECT a.*,u.username installer FROM audits a JOIN users u ON u.id=a.user_id WHERE user_id=? ORDER BY a.id DESC LIMIT 500').all(req.user.sub)));
const staticDir=resolve(process.env.STATIC_DIR||'/app/public');if(!existsSync(staticDir))throw new Error(`STATIC_DIR not found: ${staticDir}`);app.use(express.static(staticDir,{index:'index.html',extensions:['html'],maxAge:process.env.NODE_ENV==='production'?'1h':0}));app.get('/',(req,res)=>res.sendFile(resolve(staticDir,'index.html')));app.use((req,res,next)=>{if(req.path.startsWith('/api/'))return res.status(404).json({error:'not_found'});if(req.method==='GET'&&req.accepts('html'))return res.sendFile(resolve(staticDir,'index.html'));next()});app.listen(Number(process.env.PORT||8787));